#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Function to handle SIGTERM signal
sigterm_handler()
{
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
sigint_handler()
{
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
sigquit_handler()
{
    echo "Deleting PID file and terminating"
    rm /var/run/myscript.pid
    exit
}

# Trap signals and associate them with corresponding functions
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

# Write PID to file
echo $$ > /var/run/myscript.pid

# Loop indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 1
done
