#!/usr/bin/env bash
# This script prints "Best School" 10 times
# on the 9th time, it displays "Hi" followed by "Best School"

i=0

while [ $i -lt 10 ]
do
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done