#!/usr/bin/env bash
# This script prints "Best School" 10 times. it displays:
# "bad luck" on 4th iteration
# "good luck" on 8th iteration
# otherwise, it displays "Best School"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	fi
	echo "Best School"
done